version: '2'
services:
  devlibrary-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/DevLibrary/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=DevLibrary
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
